baseurl = "https://www.strichliste.org"
locale = "en-us"
title = "Strichliste ‒ The Tally Sheet Replacement for Your Organization"
theme = "hckspc-bootstrap"
disableKinds = ["taxonomy", "term"]

[[menu.main]]
  weight = 10
  name = "Home"
  pageRef = "/"

[[menu.main]]
  weight = 20
  name = "About"
  pageRef = "/about"

[[menu.main]]
  weight = 30
  name = "Install"
  pageRef = "/install"

[[menu.main]]
  weight = 35
  name = "Docs"
  pageRef = "/docs"

[[menu.main]]
  weight = 40
  name = "Demo"
  url = "https://demo.strichliste.org"

[[menu.main]]
  weight = 50
  name = "Source"
  url = "https://github.com/strichliste"

[[menu.main]]
  weight = 60
  name = "FAQ"
  pageRef = "/faq"

[markup]
  [markup.highlight]
    style = "github"

[params]
  logo = "/img/strichliste-logo.png"
  description = "strichliste is the digital tally sheet for hackerspaces, club rooms and small offices: manage your kiosk in a breeze."
