baseurl = "https://www.strichliste.org"
locale = "en-us"
title = "Strichliste ‒ The Tally Sheet Replacement for Your Organization"
theme = "hckspc-bootstrap"

[[menu.main]]
  weight = 10
  name = "Home"
  pageRef = "/"

[[menu.main]]
  weight = 20
  name = "About"
  pageRef = "/about"

[[menu.main]]
  weight = 30
  name = "Install"
  pageRef = "/install"

[[menu.main]]
  weight = 40
  name = "Demo"
  url = "https://demo.strichliste.org"

[[menu.main]]
  weight = 50
  name = "Source"
  url = "https://github.com/strichliste"

[[menu.main]]
  weight = 60
  name = "FAQ"
  pageRef = "/faq"

[params]
  logo = "/img/strichliste-logo.png"
